# REUSE 3.3 (https://reuse.software/spec-3.3/): the copyright and licence of
# every file, in one place, so no source file carries a header.
version = 1
SPDX-PackageName = "pkinative-cli"
SPDX-PackageSupplier = "Nizoka — Plika"
SPDX-PackageDownloadLocation = "https://github.com/Nizoka/pkinative-cli"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Nizoka — Plika (https://plika.app)"
SPDX-License-Identifier = "MIT"
