// The tarball, inspected file by file. Runs `npm pack --dry-run --json` and
// compares the files it would publish with docs/data/package-files.json; each
// packed file is also held to the rules of scripts/lib/package-files.ts on its
// own, so regenerating the manifest cannot bless a leak.
//   npm run build && npx tsx scripts/package-files.ts            check
//   npm run build && npx tsx scripts/package-files.ts --update   re-pin, then review the diff
// Exit: 0 match; 1 differs (or --update refused a forbidden file); 2 usage, no build, npm failed.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { npm } from './lib/npm.ts';
import {
    BUDGETS,
    PACKAGE_FILES_COMMAND,
    PACKAGE_FILES_MANIFEST,
    compareEntries,
    listFindings,
    manifestEntries,
    manifestShapeFindings,
    type PackageFilesManifest,
} from './lib/package-files.ts';

const ROOT = resolve(import.meta.dirname, '..');
const COMMENT = 'Every file `npm pack` publishes, pinned. Generated by scripts/package-files.ts — never hand-edited. '
    + 'role is derived from the path; sha256 is pinned for the legal texts only.';

function pack(): Array<{ path: string; mode: number }> | string {
    const run = npm(['pack', '--dry-run', '--json', '--ignore-scripts'], ROOT);
    if (run.status !== 0) return `npm pack --dry-run failed\n${run.stderr}`;
    try {
        const files = (JSON.parse(run.stdout) as Array<{ files?: Array<{ path: string; mode: number }> }>)[0]?.files;
        return Array.isArray(files) ? files : 'npm pack --dry-run --json reported no file list';
    } catch {
        return `npm pack --dry-run --json did not print JSON:\n${run.stdout.slice(0, 400)}`;
    }
}

function main(argv: readonly string[]): number {
    const update = argv.includes('--update');
    if (argv.some((a) => a !== '--update')) {
        process.stderr.write('usage: npx tsx scripts/package-files.ts [--update]\n');
        return 2;
    }
    if (!existsSync(join(ROOT, 'dist', 'cli.cjs'))) {
        process.stderr.write('package-files: dist/ is missing — run npm run build first\n');
        return 2;
    }
    const packed = pack();
    if (typeof packed === 'string') {
        process.stderr.write(`package-files: ${packed}\n`);
        return 2;
    }
    const actual = manifestEntries(packed, (p) => (existsSync(join(ROOT, p)) ? readFileSync(join(ROOT, p)) : null));
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { files?: string[]; bin?: Record<string, string> };
    const budgets = JSON.parse(readFileSync(join(ROOT, BUDGETS), 'utf8')) as Record<string, unknown>;
    const own = listFindings(actual.map((f) => f.path), pkg.files ?? [], Object.keys(budgets).filter((k) => !k.startsWith('$')), Object.values(pkg.bin ?? {}));

    if (update) {
        if (own.length > 0) {
            for (const line of own) process.stderr.write(`✗ ${line}\n`);
            process.stderr.write('package-files: refusing to pin a tarball that breaks the rules above\n');
            return 1;
        }
        const manifest: PackageFilesManifest = { $comment: COMMENT, generatedBy: PACKAGE_FILES_COMMAND, files: actual };
        writeFileSync(join(ROOT, PACKAGE_FILES_MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`);
        process.stdout.write(`package-files: wrote ${PACKAGE_FILES_MANIFEST} (${actual.length} files) — review the diff\n`);
        return 0;
    }
    const pinned = (JSON.parse(readFileSync(join(ROOT, PACKAGE_FILES_MANIFEST), 'utf8')) as PackageFilesManifest).files;
    const findings = [...own, ...manifestShapeFindings(pinned), ...compareEntries(pinned, actual)];
    if (findings.length > 0) {
        for (const line of findings) process.stderr.write(`✗ ${line}\n`);
        process.stderr.write(`package-files: the tarball differs from ${PACKAGE_FILES_MANIFEST}; if intended, run ${PACKAGE_FILES_COMMAND} and review the diff\n`);
        return 1;
    }
    process.stdout.write(`package-files: ${actual.length} files, exactly the ${PACKAGE_FILES_MANIFEST} list\n`);
    return 0;
}

process.exitCode = main(process.argv.slice(2));
